<?php
require __DIR__.'/../core-patch/api-platform2/modules/helpers/gateway.php';
require __DIR__.'/../reference/api-platform2/modules/helpers/log-sanitizer.php';
require __DIR__.'/../core-patch/api-platform2/modules/helpers/storage.php';
require __DIR__.'/../plugins/sovereign-freedomapi-bridge/sovereign-freedomapi-bridge.php';
$postmeta=[100=>['_freedomapi_sensitive_data_api'=>1,'apiplatform_gateway_runtime_type'=>'sovereign','_sovereign_host'=>'https://data.test','apiplatform_gateway_cache_enabled'=>1],101=>['apiplatform_gateway_cache_enabled'=>1]];
$options['sv_clients']=[$id=>['name'=>'Test','secret_hash'=>hash('sha256',$secret),'redirect_uri'=>$callback,'allowed'=>Sovereign_Host::scopes()]];
$req=new APIPlatform_Gateway_Request();$req->api_id=100;$req->source='gateway';$req->method='GET';$req->version='v1';$req->route_parts=['publisher','personal-data','v1/data'];$req->headers=['authorization'=>'Bearer PLATFORM-KEY','x-access-token'=>str_repeat('a',64)];$req->auth_context=['auth_type'=>'application','application_id'=>1,'application_key_id'=>2];
APIPlatform_Gateway::register_callback('sovereign',[Sovereign_FreedomAPI_Bridge::class,'run']);
$http_response=['status'=>200,'body'=>'{"data":{"interests":"Gaming"},"revision":2}'];$response=APIPlatform_Runtime::execute($req);
check($response instanceof APIPlatform_Gateway_Response&&$response->body['data']['interests']==='Gaming','Actual Core runtime invokes native bridge');
check($http_last[1]['headers']['Authorization']==='Bearer '.str_repeat('a',64)&&!str_contains(json_encode($http_last),'PLATFORM-KEY'),'Host receives user token; platform key stays at Core');
check($response->headers['Cache-Control']==='no-store','Native data response is no-store');
$called_transients=0;function get_transient($k){$GLOBALS['called_transients']++;return ['body'=>['data'=>'cached']];}function set_transient(...$a){$GLOBALS['called_transients']++;return true;}
check(APIPlatform_Cache_Service::get($req)===null,'Sensitive API bypasses existing shared cache even if cache setting enabled');APIPlatform_Cache_Service::set($req,$response);check($called_transients===0,'Sensitive data is never stored in Core transient cache');
$req->route_parts[2]='v1/unknown';check(denied(APIPlatform_Runtime::execute($req),404),'Native runtime rejects resolver fallback on unknown path');$req->route_parts[2]='v1/data';$req->method='DELETE';check(denied(APIPlatform_Runtime::execute($req),405),'Native runtime rejects invalid method');$req->method='GET';unset($req->headers['x-access-token']);check(denied(APIPlatform_Runtime::execute($req),401),'Native runtime requires central token');$req->headers['x-access-token']=str_repeat('a',64);
$http_response=['status'=>401,'body'=>'{"message":"revoked"}'];check(APIPlatform_Runtime::execute($req)->status===401,'Native runtime preserves central revocation denial');
$req->route_parts[2]='v1/token';$req->method='POST';$req->json=['grant_type'=>'authorization_code','client_id'=>$id,'client_secret'=>$secret,'redirect_uri'=>$callback,'code'=>str_repeat('a',64),'code_verifier'=>str_repeat('b',64),'unexpected'=>'drop'];$req->body=json_encode($req->json);$http_response=['status'=>200,'body'=>'{"access_token":"test"}'];APIPlatform_Runtime::execute($req);$sent=json_decode($http_last[1]['body'],true);check(isset($sent['code_verifier'])&&!isset($sent['unexpected'])&&!isset($http_last[1]['headers']['Authorization']),'Token exchange forwards only allowed body fields');
$log_columns=['request_headers','query_params','request_body','response_headers','response_body','request_id','auth_type'];$defs='id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,api_id INTEGER,endpoint TEXT,method TEXT,ip TEXT,status INTEGER,response_time REAL,created_at TEXT,'.implode(',',array_map(fn($c)=>$c.' TEXT',$log_columns));$wpdb->pdo->exec('CREATE TABLE wp_apiplatform_logs ('.$defs.')');
$context=['request_headers'=>['X-Access-Token'=>'USER-TOKEN'],'request_body'=>json_encode(['grant_type'=>'authorization_code','code'=>'ONE-TIME-CODE','code_verifier'=>'PRIVATE-VERIFIER','data'=>['interests'=>'PERSONAL-INTEREST']]),'response_body'=>['data'=>['profile'=>'PERSONAL-PROFILE'],'access_token'=>'USER-TOKEN'],'request_content_type'=>'application/json','response_content_type'=>'application/json'];
apiplatform_log_api_request(1,100,'personal-data',200,microtime(true),$context);$saved=$wpdb->get_row('SELECT * FROM wp_apiplatform_logs WHERE id=1');check(!str_contains(json_encode($saved),'USER-TOKEN')&&!str_contains(json_encode($saved),'PERSONAL')&&!str_contains(json_encode($saved),'PRIVATE-VERIFIER')&&!str_contains(json_encode($saved),'ONE-TIME-CODE'),'Actual Core logger omits all personal data and auth material');
$context['request_headers']=[];apiplatform_log_api_request(0,0,'invalid-route',401,microtime(true),$context);$saved=$wpdb->get_row('SELECT * FROM wp_apiplatform_logs WHERE id=2');check(!str_contains(json_encode($saved),'ONE-TIME-CODE')&&!str_contains(json_encode($saved),'PRIVATE-VERIFIER'),'Failed route token exchanges also suppress secrets');
$context=['request_body'=>['hello'=>'normal'],'request_content_type'=>'application/json','response_body'=>['hello'=>'world'],'response_content_type'=>'application/json'];apiplatform_log_api_request(1,101,'ordinary',200,microtime(true),$context);$saved=$wpdb->get_row('SELECT * FROM wp_apiplatform_logs WHERE id=3');check(str_contains($saved['response_body'],'world'),'Ordinary API history behavior remains intact');
$options['sv_connector']=['api'=>'https://api.test/gateway/publisher/personal-data/v1','gateway_key'=>Sovereign_Connector::encrypt('PLATFORM-KEY')];$http_response=['status'=>200,'body'=>'{"data":{},"revision":1}'];Sovereign_Connector::request('data','GET',null,str_repeat('c',64));check($http_last[1]['headers']['Authorization']==='Bearer PLATFORM-KEY'&&$http_last[1]['headers']['X-Access-Token']===str_repeat('c',64),'Connector separates platform credential from user token');
