<?php
require __DIR__ . '/bootstrap.php';
core_load();
$config = freedomapi_get_api_configuration(10);
check(!is_wp_error($config), 'read configuration');
check(is_wp_error(freedomapi_get_api_configuration(11)), 'cross-user access denied');
check(is_wp_error(freedomapi_get_api_configuration(999)), 'invalid API denied');
$GLOBALS['deny_schema'] = true;
check(is_wp_error(freedomapi_get_api_configuration(10)), 'schema permission required');
$GLOBALS['deny_schema'] = false;
$plan = plan(op('move', ['full_name'], ['name']), op('set', ['profile', 'active'], [], 'true'), op('remove', ['nullable']), op('copy', ['years'], ['profile', 'age']));
$preview = freedomapi_preview_transformation(10, $plan, $config['fingerprint']);
check(!is_wp_error($preview) && $preview['proposed']->full_name === 'Ada' && $preview['proposed']->years === 37, 'all operations');
check(isset($preview['original']->name) && !isset($preview['original']->full_name), 'original preserved');
check(freedomapi_validate_response_schema($preview['proposed'], $preview['output_schema']), 'inferred schema valid');
$bad = clone $preview['proposed']; $bad->years = '37';
check(!freedomapi_validate_response_schema($bad, $preview['output_schema']), 'strict type validation');
check(is_wp_error(freedomapi_execute_transformation($config['source'], plan(op('eval', ['x'])))), 'code operation rejected');
check(is_wp_error(freedomapi_execute_transformation($config['source'], plan(op('set', ['missing','x'], [], '1')))), 'missing parent rejected');
check(is_wp_error(freedomapi_execute_transformation($config['source'], plan(op('move', ['profile','x'], ['profile'])))), 'self descendant move rejected');
check(is_wp_error(freedomapi_execute_transformation($config['source'], plan(op('set', ['__proto__'], [], '1')))), 'unsafe property rejected');
check(is_wp_error(freedomapi_execute_transformation($config['source'], plan(op('set', ['x'], [], '{bad')))), 'invalid literal rejected');
check(is_wp_error(freedomapi_execute_transformation($config['source'], ['version'=>1,'operations'=>array_fill(0,33,op('set',['x'],[],'1'))])), 'operation bound');
$approved = freedomapi_update_api_configuration(10, $plan, $config['fingerprint']);
check(!is_wp_error($approved) && $approved['revision'] === 1, 'approval persists');
check(is_wp_error(freedomapi_update_api_configuration(10, $plan, $config['fingerprint'])), 'stale approval rejected');
$body = freedomapi_transform_response(10, $config['source'], 'v1');
check(!is_wp_error($body) && $body->full_name === 'Ada', 'runtime executes with no AI plugin');
check(freedomapi_transform_response(10, $config['source'], 'v2') === $config['source'], 'version scope');
check(freedomapi_transform_response(10, $config['source'], 'v1', 400) === $config['source'], 'error response unchanged');
$schema = APIPlatform_Endpoint_Schema_Service::current_schema(10);
$validation = APIPlatform_Endpoint_Schema_Service::validate_response(10, $schema['endpoints'][0], 200, 'application/json', $body);
check($validation['valid'] && $validation['mode'] === 'enforce', 'approved contract supersedes old response contract');
$config = freedomapi_get_api_configuration(10);
$GLOBALS['fail_storage'] = true;
check(is_wp_error(freedomapi_rollback_api_configuration(10, $config['fingerprint'])), 'storage failure surfaces');
$GLOBALS['fail_storage'] = false;
$rolled = freedomapi_rollback_api_configuration(10, $config['fingerprint']);
check(!is_wp_error($rolled) && $rolled['revision'] === 2, 'rollback restores previous state');
check(freedomapi_transform_response(10, $config['source'], 'v1') === $config['source'], 'baseline runtime after rollback');
$config = freedomapi_get_api_configuration(10);
$GLOBALS['meta'][10]['api_json'] = '{"name":"Edited"}';
check(is_wp_error(freedomapi_update_api_configuration(10, $plan, $config['fingerprint'])), 'manual Core edit invalidates preview');
echo "\nCore: {$GLOBALS['checks']} checks passed.\n";
