<?php
require __DIR__ . '/bootstrap.php';
core_load();
$root = getenv('FREEDOMAPI_CORE_PATH') ?: dirname(__DIR__, 2) . '/api-platform2';
require $root . '/modules/helpers/gateway.php';
require $root . '/modules/helpers/openapi.php';
$GLOBALS['meta'][10]['api_json'] = json_encode((object) ['name'=>'Ada','empty'=>new stdClass(),'list'=>[],'path'=>'C:\\folder']);
$GLOBALS['meta'][10]['apiplatform_gateway_cache_enabled'] = 1;
$config = freedomapi_get_api_configuration(10);
$request = new APIPlatform_Gateway_Request();
$request->api_id = 10; $request->owner_id = 1; $request->version = 'v1';
$request->auth_context = ['auth_type'=>'application','application_id'=>5,'application_key_id'=>7];
$raw = APIPlatform_Runtime::execute($request);
check(is_array($raw->body), 'unmodified Core runtime keeps associative arrays');
APIPlatform_Cache_Service::set($request, $raw);
check(APIPlatform_Cache_Service::get($request) !== null, 'raw response cached');
$plan = plan(op('move',['full_name'],['name']),op('set',['quoted'],[],json_encode('C:\new\"quoted"')));
$applied = freedomapi_update_api_configuration(10, $plan, $config['fingerprint']);
check(!is_wp_error($applied), 'approved with empty objects and escaped literals');
check(APIPlatform_Cache_Service::get($request) === null, 'approval invalidates old cache key');
$raw = APIPlatform_Runtime::execute($request);
check(is_object($raw->body) && is_object($raw->body->empty) && is_array($raw->body->list), 'runtime preserves JSON shapes');
APIPlatform_Cache_Service::set($request, $raw);
$fresh = freedomapi_transform_response(10, $raw->body, 'v1');
$cached = APIPlatform_Cache_Service::get($request);
$hit = freedomapi_transform_response(10, $cached['body'], 'v1');
check(!is_wp_error($fresh) && json_encode($fresh) === json_encode($hit), 'cache hits and misses transform exactly once');
check($fresh->path === 'C:\folder' && $fresh->quoted === 'C:\new\"quoted"', 'backslashes and quotes survive storage');
check(property_exists($cached['body'], 'name'), 'cache retains untransformed response');
$schema = APIPlatform_Endpoint_Schema_Service::current_schema(10);
$export = new ReflectionMethod('APIPlatform_OpenAPI_Service', 'export_responses');
$exported = $export->invoke(null, $schema['endpoints'][0]['responses']);
check(isset($exported['200']['content']['application/json']['schema']['properties']->full_name), 'OpenAPI exports approved schema');
check($exported['200']['content']['application/json']['example']->full_name === 'Ada', 'OpenAPI exports proposed example');
$current = freedomapi_get_api_configuration(10);
check(!is_wp_error(freedomapi_rollback_api_configuration(10, $current['fingerprint'])), 'rollback succeeds');
check(APIPlatform_Cache_Service::get($request) === null, 'rollback invalidates transformed generation cache');
check(is_array(APIPlatform_Runtime::execute($request)->body), 'rollback returns original runtime semantics');
echo "\nRuntime: {$GLOBALS['checks']} checks passed.\n";
