<?php
require __DIR__ . '/bootstrap.php';
core_load();
require __DIR__ . '/../freedomapi-ai/includes/class-connection.php';
require __DIR__ . '/../freedomapi-ai/includes/class-openai.php';
require __DIR__ . '/../freedomapi-ai/includes/class-plugin.php';
function send($operation, $data = [], $id = 10, $nonce = 'valid-nonce') { return FreedomAPI_AI_Plugin::dispatch($operation, new Test_Request($id, $data, 'POST', $nonce)); }
function propose($fingerprint) {
    unset($GLOBALS['transients']['freedomapi_ai_generation_' . get_current_user_id() . '_cooldown']);
    return send('proposals', ['instruction'=>'Rename name', 'consent'=>true, 'fingerprint'=>$fingerprint]);
}
check(FreedomAPI_AI_Plugin::compatible(), 'Core compatible');
FreedomAPI_AI_Plugin::boot();
check(isset($GLOBALS['actions']['rest_api_init'], $GLOBALS['filters']['freedomapi_api_management_sections']), 'features registered');
check(is_wp_error(send('configuration', [], 10, 'invalid')), 'nonce required for read');
check(is_wp_error(send('connection', ['key'=>'sk-test-abcdefghijklmnop','model'=>'gpt-4.1-mini'], 11)), 'connection route API authorization');
$GLOBALS['user'] = 0;
check(is_wp_error(send('configuration')), 'anonymous denied');
$GLOBALS['user'] = 1;
send('connection', ['key'=>'sk-test-abcdefghijklmnop','model'=>'gpt-4.1-mini']);
$config = send('configuration');
$plan = plan(op('move', ['full_name'], ['name']));
$GLOBALS['http_response'] = ['response'=>['code'=>200], 'body'=>json_encode(['status'=>'completed', 'output'=>[['type'=>'message','content'=>[['type'=>'output_text','text'=>json_encode($plan)]]]]])];
check(is_wp_error(send('proposals', ['instruction'=>'rename'])), 'consent required');
$proposal = propose($config['fingerprint']);
check(!is_wp_error($proposal) && strlen($proposal['proposal_id']) === 48, 'proposal generated');
check(freedomapi_get_api_configuration(10)['revision'] === 0, 'generation makes no Core change');
check($proposal['original']->name === 'Ada' && $proposal['proposed']->full_name === 'Ada', 'two previews');
check(is_wp_error(send('proposals', ['instruction'=>'rename','consent'=>true,'fingerprint'=>$config['fingerprint']])), 'generation cooldown');
check(is_wp_error(send('approve', ['proposal_id'=>$proposal['proposal_id']])), 'explicit approval required');
check(is_wp_error(send('approve', ['proposal_id'=>$proposal['proposal_id'],'approved'=>'true'])), 'approval must be boolean');
$GLOBALS['user'] = 2;
check(is_wp_error(send('approve', ['proposal_id'=>$proposal['proposal_id'],'approved'=>true], 11)), 'proposal bound to user and API');
$GLOBALS['user'] = 1;
$result = send('approve', ['proposal_id'=>$proposal['proposal_id'],'approved'=>true,'plan'=>plan(op('set',['pwned'],[],'true'))]);
check(!is_wp_error($result) && $result['revision'] === 1, 'approval applied');
$current = freedomapi_get_api_configuration(10);
check($current['active']['plan'] === $plan, 'browser cannot replace reviewed plan');
check(is_wp_error(send('approve', ['proposal_id'=>$proposal['proposal_id'],'approved'=>true])), 'proposal replay rejected');
$calls = count($GLOBALS['http_calls']);
$body = freedomapi_transform_response(10, $current['source'], 'v1');
check($body->full_name === 'Ada' && count($GLOBALS['http_calls']) === $calls, 'endpoint execution makes zero AI calls');
check(is_wp_error(send('rollback', ['fingerprint'=>$current['fingerprint']])), 'rollback requires approval');
$result = send('rollback', ['fingerprint'=>$current['fingerprint'],'approved'=>true]);
check(!is_wp_error($result) && $result['revision'] === 2, 'rollback workflow');
$current = freedomapi_get_api_configuration(10);
$proposal = propose($current['fingerprint']);
$GLOBALS['transients']['freedomapi_ai_proposal_' . $proposal['proposal_id']]['expires'] = time() - 1;
check(is_wp_error(send('approve', ['proposal_id'=>$proposal['proposal_id'],'approved'=>true])), 'expired proposal rejected');
$proposal = propose($current['fingerprint']);
$GLOBALS['meta'][10]['api_json'] = '{"name":"Changed"}';
check(is_wp_error(send('approve', ['proposal_id'=>$proposal['proposal_id'],'approved'=>true])), 'Core edit after preview rejected');
$current = freedomapi_get_api_configuration(10);
$proposal = propose($current['fingerprint']);
$GLOBALS['deny_schema'] = true;
check(is_wp_error(send('approve', ['proposal_id'=>$proposal['proposal_id'],'approved'=>true])), 'revoked permission rejected');
$GLOBALS['deny_schema'] = false;
$GLOBALS['options']['freedomapi_ai_generation_1'] = time();
check(is_wp_error(propose($current['fingerprint'])), 'concurrent generation blocked');
unset($GLOBALS['options']['freedomapi_ai_generation_1']);
check(is_wp_error(send('connection', ['key'=>str_repeat('a',9000)])), 'oversized payload rejected');
echo "\nWorkflow: {$GLOBALS['checks']} checks passed.\n";
